### ISSUE TITLE
How was the spinal canal segmentation obtained?

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model-csf-seg#2]
Describe code to generate the segmentation shared at: https://github.com/ivadomed/model-csf-seg/blob/ws/fill-csf/sub-cmrrb03_T2w_canal-manual_RPI_r.zip

Note: the link above will eventually disappear (see #1)

**Comment by WilliamSirois** [comment]
La segmentation que l'on cherche à atteindre est celle du canal spinal. Pour se faire, des segmentations manuelles du CSF sont utiliser. On souhaite donc créer un code qui permet de fermer les segmentation pour avoir le canal au complet. 
La première version du code réalise un remplissage par une fermeture mais ajoute du bruit autour du CSF. 
la seconde version du code pour obtenir la segmentation du canal spinal prend en entrée la segmentation du CSF puis remplis la segmentation à partir d'un point

**Comment by jcohenadad** [comment]
> La première version du code réalise un remplissage par une fermeture mais ajoute du bruit autour du CSF.
la seconde version du code pour obtenir la segmentation du canal spinal prend en entrée la segmentation du CSF puis remplis la segmentation à partir d'un point

À quelles versions fais-tu référence ? STP ajoute un hyperlien vers chaque version du code afin qu'on puisse commenter

> La première version du code réalise un remplissage par une fermeture mais ajoute du bruit autour du CSF.

quel est le rationnel pour l'ajout du bruit? quel type de bruit?

**Comment by jcohenadad** [comment]
Je suggère aussi de discuter de strategies pour la fermeture, méthodes existantes, etc. avant de commencer à implémenter

**Comment by WilliamSirois** [comment]
> À quelles versions fais-tu référence ? STP ajoute un hyperlien vers chaque version du code afin qu'on puisse commenter

Je fais référence aux versions qui sont dans ce pull request donc à celle qui est actuellement dedans et au changement que je lui ai apporter : https://github.com/ivadomed/model-csf-seg/pull/3 Je ne sais pas si les modifications sont actuellement visible je crois que je suis en mode draft merci de me dire si le tout est visible pour toi. 
> quel est le rationnel pour l'ajout du bruit? quel type de bruit?

Je n'est pas quantifier le bruit. Il s'agit seulement des pixels ajoutés que nous avions constater ensemble dans les images obtenus par mon premier code lors de ma rencontre en zoom du 1 février.
>Je suggère aussi de discuter de strategies pour la fermeture, méthodes existantes, etc. avant de commencer à implémenter

D'accord j'avais cru comprendre que je devais essayer puis créer un pull request pour que l'on travail cela ensemble mais je peut en discuter ici d'abord si cela est plus optimal selon toi!

**Comment by jcohenadad** [comment]
> Je ne sais pas si les modifications sont actuellement visible je crois que je suis en mode draft merci de me dire si le tout est visible pour toi.

oui-- pour t'en convaincre, ouvre le lien en mode incognito:
![image](https://github.com/ivadomed/model-csf-seg/assets/2482071/1ab42d1d-058c-4807-9fdb-10367a57c8ed)

> La première version correspond donc au premier commit et la seconde au deuxième commit.

Plutôt que de parler de premier/deuxieme/etc version, utilise plutot des lien vers les commit SHA, eg: https://github.com/ivadomed/model-csf-seg/pull/3/commits/9846190e77744bdd36a1a86e8cfd0e374521dab0

Par ailleurs, utiliser les commits de git pour tester des approches différentes n'est pas une bonne méthode. Une meilleure méthode serait de créer 2 scripts différents, de les comparer/discuter dans la PR, et avant de merger, ne garder que celui qui fonctionne bien.

> Je n'est pas quantifier le bruit. Il s'agit seulement des pixels ajoutés que nous avions constater ensemble dans les images obtenus par mon premier code lors de ma rencontre en zoom du 1 février.

voir ma suggestion: https://github.com/ivadomed/model-csf-seg/pull/3#discussion_r1479158114

> D'accord j'avais cru comprendre que je devais essayer puis créer un pull request pour que l'on travail cela ensemble mais je peut en discuter ici d'abord si cela est plus optimal selon toi!

Non ça va-- je voulais simplement te suggérer de faire du _brainstorming_, poser des questions, proposer des approches, etc. plutôt que de juste commit du code.
